# Generated by Django 3.2.7 on 2021-09-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='イメージ'),
        ),
    ]
