# Generated by Django 3.2.7 on 2021-10-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photopost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
